import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Login from "@/components/Login";
import Logout from "@/components/Logout";
import { useAuthState } from "react-firebase-hooks/auth";
import { auth } from "@/firebase";
import Link from "next/link";

export default function Home() {
  const [user] = useAuthState(auth);
  return (
    <>
      <Head>
        <title>Take My Stuff</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            <code>
              A place to track your things and take your friend's things
            </code>
          </p>
          <div>{user ? <Logout /> : <Login />}</div>
          <div>{user && <Link href={"/add-items"}>Add Items</Link>}</div>
        </div>

        <div className={styles.center}>
          <h1>Take My Stuff</h1>
        </div>

        <div className={styles.grid}></div>
      </main>
    </>
  );
}
